@attached(member, names: named(propertiesEqual), arbitrary)
@attached(member, names: named(==), arbitrary)
@attached(member, names: named(hash), arbitrary)
@attached(member, names: named(CodingKeys), arbitrary)
@attached(member, names: named(init), arbitrary)
@attached(member, names: named(encode), arbitrary)
public macro UsefulClass(codingMembers: [String], comparableMembers: [String], uselessInitializations: String) = #externalMacro(module: "UsefulClassMacros", type: "UsefulClassMacro")
